[package]
name = "ril-bot"
version = "0.1.0"
edition = "2021"


[dependencies]
dotenv = "0.15"
regex = "1.6"
serenity = "0.11"
reqwest = "0.11"
lazy_static = "1.4"
tokio = { version = "1.20", features = ["full"] }